const menuButton=document.querySelector('.menu');const nav=document.querySelector('nav');menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',open);menuButton.textContent=open?'✕':'☰'});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.textContent='☰'}));

const cities={lucknow:{letter:'L',subtitle:'City of Tehzeeb',date:'September 2026 — Proposed Opening Edition',name:'Lucknow',tagline:'तहज़ीब के शहर में, शब्दों की एक यादगार महफ़िल।',description:'In Lucknow, conversation carries grace and every gathering has the warmth of a mehfil. The proposed opening edition celebrates Hindi-Urdu expression, humour, poetry and refinement.'},bhopal:{letter:'B',subtitle:'City of Lakes',date:'November 2026 — Proposed Edition',name:'Bhopal',tagline:'Thoughtful words. Powerful voices. Shared emotion.',description:'Bhopal will host a carefully curated evening of poetry, humour, reflection and contemporary expression in a premium auditorium setting.'},jaipur:{letter:'J',subtitle:'The Pink City',date:'January / February 2027 — Proposed Edition',name:'Jaipur',tagline:'Tradition, expression and city pride on one stage.',description:'The Jaipur edition will celebrate the enduring relationship between language, performance, community and cultural identity.'},patna:{letter:'P',subtitle:'A city of engaged minds',date:'January / February 2027 — Proposed Edition',name:'Patna',tagline:'Memorable words for an audience deeply connected with Hindi.',description:'The Patna edition will bring humour, lyrical poetry, powerful expression and social observation to a highly engaged audience.'},delhi:{letter:'D',subtitle:'Grand Finale',date:'March 2027 — Proposed Grand Finale',name:'Delhi',tagline:'The journey culminates in its biggest celebration.',description:'The Delhi edition is planned as the flagship grand finale, bringing together leading voices and the collective energy of the entire series.'}};

document.querySelectorAll('.city-tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.city-tabs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const c=cities[btn.dataset.city];document.getElementById('city-letter').textContent=c.letter;document.getElementById('city-subtitle').textContent=c.subtitle;document.getElementById('city-date').textContent=c.date;document.getElementById('city-name').textContent=c.name;document.getElementById('city-tagline').textContent=c.tagline;document.getElementById('city-description').textContent=c.description;document.getElementById('city-cta').textContent=`Notify Me About ${c.name}`;document.querySelector('[name="city"]').value=c.name}));

const tiers={presenting:['Lead the cultural association','Premium naming and visibility across the proposed event journey, subject to final deliverables and city selection.'],powered:['Build high-frequency brand presence','Prominent on-ground and digital integration across selected cities and content formats.'],associate:['Own meaningful audience touchpoints','A balanced mix of stage visibility, hospitality and content-led association.'],city:['Celebrate a city with cultural relevance','A locally rooted partnership aligned with the identity and audiences of a selected host city.'],digital:['Extend the experience beyond the auditorium','Digital-first integrations across video, social content, edits and event microsite visibility.']};document.querySelectorAll('.tier').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tier').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const [title,copy]=tiers[btn.dataset.tier];document.getElementById('tier-title').textContent=title;document.getElementById('tier-copy').textContent=copy}));

document.querySelectorAll('.faq-item button').forEach(btn=>btn.addEventListener('click',()=>btn.parentElement.classList.toggle('open')));

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

document.getElementById('interest-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;const status=document.getElementById('form-status');if(!form.checkValidity()){status.textContent='Please complete all required fields.';status.style.color='#a62a2a';form.reportValidity();return}status.textContent='आपका स्वागत है। Your interest has been registered in this demo.';status.style.color='#24613f';form.reset()});
